// This file is automatically generated.

interface CssExports {
  'layout': string;
  'logo': string;
  'logoImg': string;
  'logoImgCollapsed': string;
  'logoText': string;
  'logo__img': string;
  'logo__img--collapsed': string;
  'logo__text': string;
}

declare var cssExports: CssExports;
export = cssExports;
