// This file is automatically generated.

interface CssExports {
  'button': string;
  'buttons': string;
  'counter': string;
  'row': string;
}

declare var cssExports: CssExports;
export = cssExports;
